stages:
  - initialize
  - deploy
initialize:
  stage: initialize
  image: node:latest
  script:
    - git subtree push --prefix ecofresh/client/ heroku main
    - echo "Deployed to heroku server"
  environment:
    name: production
    url: https://group10-ecofresh.herokuapp.com/
  only:
    - main