stages:
  - initialize
  - deploy

initialize:
  stage: initialize
  image: node:latest
  script:
    - cd ecofresh/client
    - npm install

deploy_production:
  image: node:latest
  stage: deploy
  script:
    - git subtree push --prefix ecofresh/client https://$HEROKU_USER:$HEROKU_API_KEY@git.heroku.com/group10-ecofresh.git HEAD:master
    - echo "Deployed to heroku server"
  environment:
    name: production
    url: https://group10-ecofresh.herokuapp.com/
  only:
    - main
